/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbstractsRouteImport } from './routes/abstracts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as RegistrationSuccessRouteImport } from './routes/registration-success'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SubmitAbstractRouteImport } from './routes/submit-abstract'
import { Route as VenueRouteImport } from './routes/venue'
import { Route as WorkshopsRouteImport } from './routes/workshops'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbstractsRoute = AbstractsRouteImport.update({
  id: '/abstracts',
  path: '/abstracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationSuccessRoute = RegistrationSuccessRouteImport.update({
  id: '/registration-success',
  path: '/registration-success',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitAbstractRoute = SubmitAbstractRouteImport.update({
  id: '/submit-abstract',
  path: '/submit-abstract',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueRoute = VenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abstracts': typeof AbstractsRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/program': typeof ProgramRoute
  '/register': typeof RegisterRoute
  '/registration': typeof RegistrationRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/speakers': typeof SpeakersRoute
  '/sponsors': typeof SponsorsRoute
  '/submit-abstract': typeof SubmitAbstractRoute
  '/venue': typeof VenueRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abstracts': typeof AbstractsRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/program': typeof ProgramRoute
  '/register': typeof RegisterRoute
  '/registration': typeof RegistrationRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/speakers': typeof SpeakersRoute
  '/sponsors': typeof SponsorsRoute
  '/submit-abstract': typeof SubmitAbstractRoute
  '/venue': typeof VenueRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abstracts': typeof AbstractsRoute
  '/contact': typeof ContactRoute
  '/leadership': typeof LeadershipRoute
  '/program': typeof ProgramRoute
  '/register': typeof RegisterRoute
  '/registration': typeof RegistrationRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/speakers': typeof SpeakersRoute
  '/sponsors': typeof SponsorsRoute
  '/submit-abstract': typeof SubmitAbstractRoute
  '/venue': typeof VenueRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abstracts'
    | '/contact'
    | '/leadership'
    | '/program'
    | '/register'
    | '/registration'
    | '/registration-success'
    | '/speakers'
    | '/sponsors'
    | '/submit-abstract'
    | '/venue'
    | '/workshops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abstracts'
    | '/contact'
    | '/leadership'
    | '/program'
    | '/register'
    | '/registration'
    | '/registration-success'
    | '/speakers'
    | '/sponsors'
    | '/submit-abstract'
    | '/venue'
    | '/workshops'
  id:
    | '__root__'
    | '/'
    | '/abstracts'
    | '/contact'
    | '/leadership'
    | '/program'
    | '/register'
    | '/registration'
    | '/registration-success'
    | '/speakers'
    | '/sponsors'
    | '/submit-abstract'
    | '/venue'
    | '/workshops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbstractsRoute: typeof AbstractsRoute
  ContactRoute: typeof ContactRoute
  LeadershipRoute: typeof LeadershipRoute
  ProgramRoute: typeof ProgramRoute
  RegisterRoute: typeof RegisterRoute
  RegistrationRoute: typeof RegistrationRoute
  RegistrationSuccessRoute: typeof RegistrationSuccessRoute
  SpeakersRoute: typeof SpeakersRoute
  SponsorsRoute: typeof SponsorsRoute
  SubmitAbstractRoute: typeof SubmitAbstractRoute
  VenueRoute: typeof VenueRoute
  WorkshopsRoute: typeof WorkshopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abstracts': {
      id: '/abstracts'
      path: '/abstracts'
      fullPath: '/abstracts'
      preLoaderRoute: typeof AbstractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-success': {
      id: '/registration-success'
      path: '/registration-success'
      fullPath: '/registration-success'
      preLoaderRoute: typeof RegistrationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-abstract': {
      id: '/submit-abstract'
      path: '/submit-abstract'
      fullPath: '/submit-abstract'
      preLoaderRoute: typeof SubmitAbstractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue': {
      id: '/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof VenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbstractsRoute: AbstractsRoute,
  ContactRoute: ContactRoute,
  LeadershipRoute: LeadershipRoute,
  ProgramRoute: ProgramRoute,
  RegisterRoute: RegisterRoute,
  RegistrationRoute: RegistrationRoute,
  RegistrationSuccessRoute: RegistrationSuccessRoute,
  SpeakersRoute: SpeakersRoute,
  SponsorsRoute: SponsorsRoute,
  SubmitAbstractRoute: SubmitAbstractRoute,
  VenueRoute: VenueRoute,
  WorkshopsRoute: WorkshopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
